import os
import json
import requests
import uvicorn
import io
import sys
import traceback
import re
import pandas as pd
import pypdf
from fastapi import FastAPI, BackgroundTasks, HTTPException
from pydantic import BaseModel
from playwright.async_api import async_playwright
from openai import OpenAI

app = FastAPI()

# --- 1. CONFIGURATION (AI Pipe & Secret) ---
AIPIPE_TOKEN = os.environ.get("AIPIPE_TOKEN")
MY_SECRET = os.environ.get("MY_SECRET", "hemant_secret_123")

if not AIPIPE_TOKEN:
    print("⚠️ WARNING: AIPIPE_TOKEN not found! Check Render Environment Variables.")

# Client Setup for AI Pipe
client = OpenAI(
    api_key=AIPIPE_TOKEN,
    base_url="https://aipipe.org/openrouter/v1"
)

class QuizTask(BaseModel):
    email: str
    secret: str
    url: str

# --- 2. WELCOME PAGE ---
@app.get("/")
def home():
    return {
        "status": "Active",
        "message": "AI Agent Ready. Send POST to /quiz",
        "capabilities": ["Web Scraping", "PDF Reading", "Data Analysis", "Auto-Submission"]
    }

# --- 3. HELPER: EXECUTE CODE (Upgraded for Files) ---
def execute_python_code(code_str: str):
    """
    Executes Python code generated by AI.
    Includes capability to handle PDF, CSV, Excel processing.
    """
    old_stdout = sys.stdout
    redirected_output = sys.stdout = io.StringIO()
    
    # Context dictionary: Ye libraries AI ke code mein available hongi
    exec_globals = {
        '__name__': '__main__',
        'requests': requests,
        'json': json,
        're': re,
        'pd': pd,      # Pandas for Data Analysis
        'pypdf': pypdf, # PyPDF for PDF reading
        'io': io       # IO for handling file streams
    }
    
    try:
        print("🐍 Executing AI Code with Data Capabilities...")
        exec(code_str, exec_globals)
        return redirected_output.getvalue().strip()
    except Exception as e:
        return f"Error: {str(e)}"
    finally:
        sys.stdout = old_stdout

# --- 4. MAIN LOGIC ---
async def process_quiz_loop(start_url: str, email: str, secret: str):
    current_url = start_url
    visited_urls = set()
    print(f"🚀 Starting Quiz Loop at: {current_url}")

    while current_url and current_url not in visited_urls:
        visited_urls.add(current_url)
        print(f"\n📍 Processing Level: {current_url}")
        try:
            # A. SCRAPE (Web)
            async with async_playwright() as p:
                browser = await p.chromium.launch(headless=True)
                page = await browser.new_page()
                await page.goto(current_url)
                try: await page.wait_for_selector("body", timeout=5000)
                except: pass
                visible_text = await page.inner_text("body")
                # Also get all links for file downloads
                links = await page.evaluate("""() => {
                    return Array.from(document.querySelectorAll('a')).map(a => a.href);
                }""")
                await browser.close()
                print("✅ Page Scraped.")

            # B. ASK AI PIPE (With File Instructions)
            prompt = f"""
            You are an expert Data Analyst Python Bot.
            
            Current Webpage Text:
            ---
            {visible_text[:6000]}
            ---
            Links found on page: {links}
            
            YOUR MISSION:
            1. Read the question carefully.
            2. If the question requires data from a file (PDF/CSV/Link), write code to DOWNLOAD it using `requests` and `io`.
               - For PDFs: Use `pypdf.PdfReader(io.BytesIO(response.content))`
               - For CSVs: Use `pd.read_csv(io.BytesIO(response.content))`
            3. Calculate the exact answer.
            4. Identify the submission URL.
            
            CRITICAL OUTPUT RULES:
            - Output ONLY raw Python code. No markdown.
            - The code MUST print a valid JSON string at the end: {{"answer": <value>, "submission_url": "<url>"}}
            """

            print(f"🤖 Asking AI Pipe (Data Mode)...")
            response = client.chat.completions.create(
                model="openai/gpt-4o-mini", 
                messages=[{"role": "user", "content": prompt}]
            )
            ai_code = response.choices[0].message.content.replace("```python", "").replace("```", "").strip()
            
            # C. EXECUTE
            execution_result = execute_python_code(ai_code)
            print(f"⚡ Result: {execution_result}")

            # D. PARSE & SUBMIT
            submit_url = None
            answer = None
            try:
                # Find JSON structure in output
                match = re.search(r'\{.*\}', execution_result, re.DOTALL)
                if match:
                    data = json.loads(match.group())
                    answer = data.get("answer")
                    submit_url = data.get("submission_url")
                    
                    # Handle relative URLs
                    if submit_url and not submit_url.startswith("http"):
                        from urllib.parse import urljoin
                        submit_url = urljoin(current_url, submit_url)
            except: pass

            if not submit_url:
                print("❌ Submission URL not found in AI output."); break

            payload = {"email": email, "secret": secret, "url": current_url, "answer": answer}
            print(f"📤 Submitting to {submit_url}...")
            
            # Submit
            res = requests.post(submit_url, json=payload, timeout=10).json()
            print(f"✅ Response: {res}")
            
            # Check for Next Level
            if res.get("correct") == True and "url" in res:
                current_url = res["url"]
            else:
                print("🏁 Quiz Finished.")
                current_url = None

        except Exception as e:
            print(f"🔥 Error: {e}"); traceback.print_exc(); current_url = None

# --- 5. API ENDPOINT ---
@app.post("/quiz")
async def receive_task(task: QuizTask, background_tasks: BackgroundTasks):
    if task.secret != MY_SECRET: raise HTTPException(status_code=403, detail="Invalid Secret")
    background_tasks.add_task(process_quiz_loop, task.url, task.email, task.secret)
    return {"message": "AI Agent (Data Capable) started."}

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)
